# Generated by Django 5.2.13 on 2026-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('COMPARATIVOS', 'COMPARATIVOS'), ('SERVICIOS OBRA', 'SERVICIOS OBRA'), ('DISEÑO', 'DISEÑO'), ('MERCADEO', 'MERCADEO')], default='COMPARATIVOS', max_length=30),
        ),
    ]
